### ISSUE TITLE
Import error on module coverage.py

### ISSUE THREAD

**Issue by ssosas** [pylayers/pylayers#256]
The next error is obtained when I try to import module coverage.py for calculating indoor coverage:

>>> from pylayers.antprop.coverage import *
mayavi not installed 
Layout:Mayavi is not installed 
Layout:Mayavi is not installed 
Traceback (most recent call last): 
File "<stdin>", line 1, in <module> 
File "build/bdist.linux-x86_64/egg/pylayers/antprop/coverage.py", line 25, in <module> 
ImportError: No module named deygout 
>>> 

Thanks for your help! Best regards,

Sergio SOSA

**Comment by buguen** [comment]
The dégoût module is now versioned. Get the last version of the master branch and it should work.
Notice that coverage for outdoor propagation is still in beta version.
