### ISSUE TITLE
ValueError in gui/editor.py

### ISSUE THREAD

**Issue by Mornyres** [pylayers/pylayers#313]
I'm trying to run `pylayers/gui/editor.py`. When I click `New Layout > New` I get the following error.

```
Traceback (most recent call last):
  File "editor.py", line 629, in new
    self.parent.L.boundary(xlim=lim)
  File "build/bdist.linux-x86_64/egg/pylayers/gis/layout.py", line 11057, in boundary
  File "build/bdist.linux-x86_64/egg/pylayers/gis/layout.py", line 2575, in add_fnod
ValueError: min() arg is an empty sequence
```
I would also like to note that I can open and edit an existing .lay file, but there are a bunch of other errors and exiting the editor always gives a segmentation fault.

**Comment by buguen** [comment]
This is a problem which is probably related to the current python3 migration. I have push a new version which should work much better on the master branch. 
Thank you for raising those issue, this is very welcome. The editor is pretty much usable now. 
I have added a unit testing file which test all the function which as been modified to fix this issue
[test_layout_u.py](https://github.com/pylayers/pylayers/blob/master/pylayers/gis/test/test_layout_u.py)

More test are clearly needed
