### ISSUE TITLE
Error in algebraic.py: global name 'rg_ramerstd' is not defined

### ISSUE THREAD

**Issue by lquinet** [pylayers/pylayers#328]
Hi, 

When I tried to execute the file test_algebraic.py in pylayers/pylayers/location/algebraic/tests , I have an error:

```
Traceback (most recent call last):
  File "test_algebraic.py", line 52, in <module>
    print S.crb(nodes['BN'],0,1,0)
  File "build\bdist.win-amd64\egg\pylayers\location\algebraic\algebraic.py", line 1145, in crb
  File "build\bdist.win-amd64\egg\pylayers\location\algebraic\algebraic.py", line 1084, in fim
NameError: global name 'rg_ramerstd' is not defined   
```

I suspect there is an error in fim method of algloc class in algebraic.py, because we access the variable rg_ramerstd[i] which is no initialised anywhere. This error happens only when tdoa=1 in the parameter of the method.

Or perhaps something is misconfigured in my python environment? I'm on Windows 10 and I'm using an anaconda environment in python 2.7. Here is the list of the packages installed:

```
# packages in environment at C:\Users\Utilisateur\Anaconda3\envs\pylayers:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                   py27_0
apptools                  4.4.0                    py27_1
asn1crypto                0.24.0                   py27_0
astroid                   1.6.5                    py27_0
attrs                     19.1.0                   py27_1
babel                     2.6.0                    py27_0
backports                 1.0                      py27_1
backports.functools_lru_cache 1.5                      py27_1
backports.shutil_get_terminal_size 1.0.0                    py27_2
backports_abc             0.5                        py_0
basemap                   1.2.0                    pypi_0    pypi
bitstring                 3.1.5                    pypi_0    pypi
blas                      1.0                         mkl
bleach                    3.1.0                    py27_0
bzip2                     1.0.6                h0c8e037_5
ca-certificates           2019.3.9             hecc5488_0    conda-forge
certifi                   2019.3.9                 py27_0    conda-forge
cffi                      1.12.3           py27hcfb25f9_0
cftime                    1.0.3.4          py27hc997a72_0
chardet                   3.0.4                    pypi_0    pypi
click                     7.0                      pypi_0    pypi
cloudpickle               1.0.0                      py_0
colorama                  0.4.1                    pypi_0    pypi
configobj                 5.0.6                    py27_1
configparser              3.7.4                    py27_0
cryptography              2.4.2            py27hc64555f_0
curl                      7.62.0               h7a46e7a_0
cycler                    0.10.0           py27h59acbbf_0
cython                    0.29.7                   pypi_0    pypi
decorator                 4.4.0                    py27_1
defusedxml                0.6.0                      py_0
descartes                 1.1.0                    pypi_0    pypi
dill                      0.2.9                    pypi_0    pypi
django                    1.11.20                  pypi_0    pypi
docutils                  0.14             py27h8652d09_0
entrypoints               0.3                      py27_0
enum34                    1.1.6                    pypi_0    pypi
envisage                  4.7.1                      py_0
expat                     2.2.5                h2880e7c_0
freetype                  2.9.1                h4d385ea_1
freexl                    1.0.5                h0c8e037_0
functools32               3.2.3.2                  py27_1
future                    0.17.1                   pypi_0    pypi
futures                   3.2.0                    py27_0
gdal                      2.0.0                    py27_1
geocoder                  1.38.1                   pypi_0    pypi
geos                      3.6.2                heec837b_2
h5py                      2.8.0            py27h5f1a774_2
hdf4                      4.2.13               hd0a9391_2
hdf5                      1.10.2               h530792d_2
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 h2aa20d9_1
idna                      2.8                      pypi_0    pypi
image                     1.5.27                   pypi_0    pypi
imagesize                 1.1.0                    py27_0
infinity                  1.4                        py_0    conda-forge
intel-openmp              2019.3                      203
intervals                 0.8.1                      py_0    conda-forge
ipaddress                 1.0.22                   py27_0
ipykernel                 4.10.0                   py27_0
ipython                   5.8.0                    py27_0
ipython-genutils          0.2.0                    pypi_0    pypi
ipython_genutils          0.2.0            py27hbe997df_0
isort                     4.3.19                   py27_0
jedi                      0.13.3                   py27_0
jinja2                    2.10.1                   py27_0
jpeg                      9b                   ha175dff_2
jsonschema                3.0.1                    py27_0
jupyter_client            5.2.4                    py27_0
jupyter_core              4.4.0                    py27_0
kealib                    1.4.7                hbe19aa3_6
keyring                   18.0.0                   py27_0
kiwisolver                1.1.0            py27hc56fc5f_0
krb5                      1.13.2                        0
lazy-object-proxy         1.4.1            py27h0c8e037_0
libboost                  1.67.0               hab8cdc6_4
libcurl                   7.62.0               h7a46e7a_0
libgdal                   2.0.0                     vc9_1
libiconv                  1.15                 hda2e4ec_7
libkml                    1.3.0                h7e671d2_4
libnetcdf                 4.6.1                hdbafb72_2
libpng                    1.6.37               h7a46e7a_0
libpq                     9.5.4                     vc9_0
libsodium                 1.0.16               h8b3e59e_0
libspatialite             4.3.0a              hbf2645c_18
libssh2                   1.8.0                h77a7533_4
libtiff                   4.0.10               h1c3b264_2
libxml2                   2.9.9                h325896a_0
linecache2                1.0.0                    py27_0
markupsafe                1.1.1            py27h0c8e037_0
matplotlib                2.2.3            py27h263d877_0
mccabe                    0.6.1                    py27_1
mistune                   0.8.4            py27h0c8e037_0
mkl                       2019.3                      203
mkl_fft                   1.0.12           py27h44c1dab_0
multiprocess              0.70.7                   pypi_0    pypi
nbconvert                 5.5.0                      py_0
nbformat                  4.4.0            py27hf49b375_0
netcdf4                   1.4.2            py27h432e9c9_0
networkx                  2.2                      py27_1
numpy                     1.11.3          py27h239e66a_12
numpy-base                1.11.3          py27hb1d0314_12
numpydoc                  0.9.1                      py_0
openjpeg                  2.3.0                h8d199b9_1
openssl                   1.0.2r               h0c8e037_0    conda-forge
osmapi                    1.2.2                    pypi_0    pypi
packaging                 19.0                     py27_0
pandas                    0.23.4           py27h39f3610_0
pandoc                    2.2.3.2                       0
pandocfilters             1.4.2                    py27_1
parso                     0.4.0                      py_0
pathlib2                  2.3.3                    pypi_0    pypi
pathos                    0.2.3                    pypi_0    pypi
patsy                     0.5.1                    py27_0
pickleshare               0.7.5                    pypi_0    pypi
pil                       1.1.7                    py27_0
pillow                    6.0.0                    pypi_0    pypi
pip                       19.1.1                   py27_0
pox                       0.2.5                    pypi_0    pypi
ppft                      1.6.4.9                  pypi_0    pypi
proj4                     4.9.3                h3980ba1_7
prompt-toolkit            1.0.16                   pypi_0    pypi
prompt_toolkit            1.0.15           py27h3a8ec6a_0
protobuf                  3.7.1                    pypi_0    pypi
psutil                    5.6.2            py27h0c8e037_0
pycodestyle               2.5.0                    py27_0
pycparser                 2.19                     py27_0
pyface                    6.0.0                    py27_0
pyflakes                  2.1.1                    py27_0
pygments                  2.4.0                      py_0
pylint                    1.9.2                    py27_0
pyopenssl                 19.0.0                   py27_0
pyparsing                 2.4.0                      py_0
pyproj                    1.9.5.1                  py27_0
pyqt                      5.6.0            py27h6e61f57_6
pyreadline                2.1                      py27_1
pyrsistent                0.14.11          py27h0c8e037_0
pyshp                     2.1.0                      py_0
pysocks                   1.7.0                    py27_0
python                    2.7.16               hcb6e200_0
python-dateutil           2.8.0                    py27_0
pytz                      2019.1                     py_0
pywin32                   223              py27h0c8e037_1
pyzmq                     18.0.0           py27hc56fc5f_0
qt                        5.6.2            vc9hc26998b_12
qtawesome                 0.5.7                    py27_1
qtconsole                 4.4.4                      py_0
qtpy                      1.7.1                      py_0
ratelim                   0.1.6                    pypi_0    pypi
requests                  2.22.0                   pypi_0    pypi
rope                      0.14.0                     py_0
scandir                   1.10.0           py27h0c8e037_0
scipy                     1.2.1            py27h4c3ab11_0
seaborn                   0.9.0                    py27_0
setuptools                41.0.1                   py27_0
shapely                   1.6.4.post1              pypi_0    pypi
simplegeneric             0.8.1                    pypi_0    pypi
simplekml                 1.3.1                    pypi_0    pypi
simpy                     2.2                      pypi_0    pypi
singledispatch            3.4.0.3          py27h3f9d112_0
sip                       4.18.1           py27hc56fc5f_2
six                       1.12.0                   py27_0
smopy                     0.0.6                    pypi_0    pypi
snowballstemmer           1.2.1            py27h28d3bf7_0
sphinx                    1.8.5                    py27_0
sphinxcontrib             1.0                      py27_1
sphinxcontrib-websupport  1.1.0                    py27_1
spyder                    3.3.4                    py27_0
spyder-kernels            0.4.4                    py27_0
sqlite                    3.28.0               h0c8e037_0
statsmodels               0.9.0            py27hc997a72_0
testpath                  0.4.2                    py27_0
tk                        8.5.18                    vc9_0
tornado                   5.1.1            py27h0c8e037_0
tqdm                      4.32.1                   pypi_0    pypi
traceback2                1.4.0                    py27_0
traitlets                 4.3.2                    pypi_0    pypi
traits                    5.1.1            py27h0c8e037_0
traitsui                  6.0.0                    py27_1
triangle                  20170429                 pypi_0    pypi
typing                    3.6.6                    py27_0
unittest2                 1.1.0                    py27_0
urllib3                   1.25.3                   pypi_0    pypi
vc                        9                    h7299396_1
vs2008_runtime            9.00.30729.1         hfaea7d5_1
vtk                       6.3.0                    py27_1
wcwidth                   0.1.7                    pypi_0    pypi
webencodings              0.5.1                    py27_1
wheel                     0.33.4                   py27_0
win-unicode-console       0.5                      pypi_0    pypi
win_inet_pton             1.1.0                    py27_0
win_unicode_console       0.5              py27hc037021_0
wincertstore              0.2              py27hf04cefb_0
wrapt                     1.11.1           py27h0c8e037_0
wxpython                  4.0.4            py27hc56fc5f_0
xerces-c                  3.2.2                hc56fc5f_0
xz                        5.2.4                h3cc03e0_4
zeromq                    4.3.1                h2880e7c_3
zlib                      1.2.11               h3cc03e0_3
zstd                      1.3.7                h1b0e4d7_0
```

**Comment by buguen** [comment]
I have fixed the error. It should work now.

**Comment by lquinet** [comment]
Tested in python 3.6, it works.
