### ISSUE TITLE
Coverage zceil

### ISSUE THREAD

**Issue by rafaelalexandrou** [pylayers/pylayers#331]
Using Coverage example 
`C = Coverage('coverage.ini')`

i get the following error for the last 2 weeks.  

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/pylayers/antprop/coverage.py", line 113, in __init__
  File "build/bdist.linux-x86_64/egg/pylayers/gis/layout.py", line 370, in __init__
  File "build/bdist.linux-x86_64/egg/pylayers/gis/layout.py", line 2213, in load
KeyError: 'zceil'`

I'm using master.
Thanks to anyone who will bother helping me.

**Comment by ermadhan** [comment]
In last two lines in your *.lay file, change floor and ceil to zfloor and zceil. This fixed the issue for me. for coverage.ini file, you need to go to TA-Office.lay.
