### ISSUE TITLE
problem running code 

### ISSUE THREAD

**Issue by cdd017** [pylayers/pylayers#357]
i try to run example code from the site 

i receive errors  for any import command

n [11]: runcell(0, 'C:/Users/dannyd/untitled0.py')
Traceback (most recent call last):

  File "C:\Users\dannyd\untitled0.py", line 8, in <module>
    from pylayers.gis.ezone import *

  File "<frozen zipimport>", line 259, in load_module

  File "C:\Users\dannyd\Anaconda3\envs\pyl38\lib\site-packages\pylayers-0.5-py3.8.egg\pylayers\gis\ezone.py", line 24, in <module>
    import pylayers.util.geomutil as geu

  File "<frozen zipimport>", line 259, in load_module

  File "C:\Users\dannyd\Anaconda3\envs\pyl38\lib\site-packages\pylayers-0.5-py3.8.egg\pylayers\util\geomutil.py", line 25, in <module>
    from descartes.patch import PolygonPatch

ModuleNotFoundError: No module named 'descartes'

Pleas Help.

**Comment by shihchun** [comment]
pip install descartes

**Comment by cdd017** [comment]
No success....after pip install descartes

>>> from pylayers.gis.ezone import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\dannyd\Anaconda3\envs\pyl38\lib\site-packages\pylayers-0.5-py3.8.egg\pylayers\gis\ezone.py", line 26, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\dannyd\Anaconda3\envs\pyl38\lib\site-packages\pylayers-0.5-py3.8.egg\pylayers\antprop\loss.py", line 19, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\dannyd\Anaconda3\envs\pyl38\lib\site-packages\pylayers-0.5-py3.8.egg\pylayers\gis\gisutil.py", line 4, in <module>
ModuleNotFoundError: No module named 'simplejson'

**Comment by cdd017** [comment]
Can you address me how to run a sample program? 
pleas

**Comment by shihchun** [comment]
pip install simplejson

**Comment by shihchun** [comment]
Maybe you can try this 

```python
from pylayers.simul.link import *
import matplotlib.pyplot as plt

L=Layout('defstr.lay')
rx = np.array([8,4,1.6])
tx = np.array([2,3,1.5])
fGHz = np.linspace(2,6,500)
Aa = Antenna('Omni',fGHz=fGHz)
Ab = Antenna('Omni',fGHz=fGHz)

L.build()
L.dumpw() # <= This is the trick
L._showGi()
Lk = DLink(L=L,a=tx,b=rx,Aa=Aa,Ab=Ab,fGHz=fGHz)
Lk.eval(force=True)
Lk._show3() # Not sure 3d works on wsl and macOS or not
# other thing may need check the code
Lk.H # return Tchannel pylayers\pylayers\antprop\channel.py
Lk.H.y
Lk.H.plotd()
```

Here is the code I've tryed, but some small prob I change the source code make them works, you can try 
https://github.com/shihchun/pylayers.git
[example.zip](https://github.com/pylayers/pylayers/files/5565663/example.zip)

**Comment by cdd017** [comment]
(pyl38) C:\Users\dannyd\pylayers-master>python
Python 3.8.3 (default, Jul  2 2020, 17:30:36) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>>
>>>
>>>
>>>
>>> from pylayers.simul.link import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\dannyd\pylayers-master\pylayers\simul\link.py", line 30, in <module>
    from pylayers.simul.radionode import RadioNode
  File "C:\Users\dannyd\pylayers-master\pylayers\simul\radionode.py", line 26, in <module>
    from pylayers.mobility.trajectory import *
  File "C:\Users\dannyd\pylayers-master\pylayers\mobility\trajectory.py", line 30, in <module>
    from pylayers.gis.layout import Layout
  File "C:\Users\dannyd\pylayers-master\pylayers\gis\layout.py", line 32, in <module>
    import triangle
ModuleNotFoundError: No module named 'triangle'

**Comment by shihchun** [comment]
pip install triangle (==
If on windows may need whl

**Comment by cdd017** [comment]
I'm running on windows,
pip install triangle already did. but no success

**Comment by shihchun** [comment]
download the whl [package ](https://www.lfd.uci.edu/~gohlke/pythonlibs/)
<img width="777" alt="image" src="https://user-images.githubusercontent.com/27427042/99644758-47e4df80-2a89-11eb-8097-6c4404bc7044.png">

[Issue354](https://github.com/pylayers/pylayers/issues/354#issuecomment-727794765) said install with pipe
