### ISSUE TITLE
[WinError 3] Access file not found error

### ISSUE THREAD

**Issue by SifalB** [pylayers/pylayers#377]
Hi everyone,

Here is my code :

```
from pylayers.gis.ezone import *
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import time
#
# Saint Pern Transmitter
#

latgw = 48.28693
longw = -1.95677
tilename = enctile(longw,latgw)
dem=DEM(enctile(longw,latgw))
dem.dwlsrtm()
xgw,ygw = dem.m(longw,latgw)
ez = Ezone(enctile(longw,latgw))
ez.hgts=dem.hgts
ez.rebase('srtm')
pa = np.array([longw,latgw])
for Ht in [50,100,150]:
    tic = time.time()
    L1 = ez.cover(pc=pa, Ht=Ht, Hr=1.5, Nr=200, Rmax=20000, method='deygout',
            source='srtm',fGHz=0.474166)
    toc = time.time()
    print(" Computation time : {:.2f} seconds".format(toc-tic))
    tc = plt.tripcolor(L1[0],-L1[1].flatten(),
                              shading='gouraud',
                              cmap='jet',
                              vmax=-60,
                              vmin=-120,
                              alpha = 1,
                              edgecolors='k',
                              linewidth=0.0)

    plt.title("Lat {:.2f}, Lon {:.2f} , Height{:.2f}".format(latgw,longw,Ht),fontsize=18)
    cb = plt.colorbar()
    cb.set_label("Loss (dB)")
    plt.axis('equal')
plt.show()
```

I got this error : 

> "C:\Users\Schifty\Documents\Script python\Propagation Radio\Scripts\python.exe" "C:/Users/Schifty/Documents/Python Scripts/Propagation Radio/main.py"
Traceback (most recent call last):
  File "C:\Users\Schifty\Documents\Python Scripts\Propagation Radio\main.py", line 1, in <module>
    from pylayers.gis.ezone import *
  File "C:\Users\Schifty\Documents\Script python\Propagation Radio\lib\site-packages\pylayers\gis\ezone.py", line 23, in <module>
    import pylayers.util.pyutil as pyu
  File "C:\Users\Schifty\Documents\Script python\Propagation Radio\lib\site-packages\pylayers\util\pyutil.py", line 62, in <module>
    from pylayers.util.project import *
  File "C:\Users\Schifty\Documents\Script python\Propagation Radio\lib\site-packages\pylayers\util\project.py", line 325, in <module>
    filelist = os.listdir(os.path.join(pylayersdir,'data', dl))
FileNotFoundError: [WinError 3] Le chemin d’accès spécifié est introuvable: 'C:\\Users\\Schifty\\AppData\\Local\\Temp\\pip-req-build-ycrtbi1y\\data\\ini'

I dont understand what i'm missing.

Thanks for your help.

**Comment by SifalB** [comment]
All good i've copied the data folder from pylayers into the folder  "pip-req-build-ycrtbi1y" and it's good.
