### ISSUE TITLE
ImportError: cannot import name 'write_gpickle' from 'networkx.readwrite' 

### ISSUE THREAD

**Issue by PedroA-Vieira** [pylayers/pylayers#394]
After installing PyLayers, when trying to run the example https://github.com/pylayers/pylayers/tree/master#installation-notes, the command in the Python:
>>>'from pylayers.simul.link import *

**gives the following error:**
>>> from pylayers.simul.link import *
Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
   File "c:\Users\pavvi\anaconda3\envs\Pylayers\pylayers\pylayers\simul\link.py", line 30, in <module>
     from pylayers.simul.radionode import RadioNode
   File "c:\Users\pavvi\anaconda3\envs\Pylayers\pylayers\pylayers\simul\radionode.py", line 26, in <module>
     from pylayers.mobility.trajectory import *
   File "c:\Users\pavvi\anaconda3\envs\Pylayers\pylayers\pylayers\mobility\trajectory.py", line 30, in <module>
     from pylayers.gis.layout import Layout
   File "c:\Users\pavvi\anaconda3\envs\Pylayers\pylayers\pylayers\gis\layout.py", line 39, in <module>
     from networkx.readwrite import write_gpickle, read_gpickle
**ImportError: cannot import name 'write_gpickle' from 'networkx.readwrite' (c:\Users\pavvi\anaconda3\envs\Pylayers\Lib\site-packages\networkx\readwrite\__init__.py)**

**The last line gives an indication of what it could be:
ImportError: cannot import name 'write_gpickle' from 'networkx.readwrite' (c:\Users\pavvi\anaconda3\envs\Pylayers\Lib\site-packages\networkx\readwrite\__init__.py)**

**What could it be and how to fix it?**

**Comment by PedroA-Vieira** [comment]
A search in the we give me this
https://stackoverflow.com/questions/76001249/module-networkx-has-no-attribute-read-gpickle

and 
[Deprecated code](https://networkx.org/documentation/stable/release/migration_guide_from_2.x_to_3.0.html#deprecated-code)

Deprecated code
The functions read_gpickle and write_gpickle were removed in 3.0. You can read and write NetworkX graphs as Python pickles.
------------------------------------------------------------
**import pickle
G = nx.path_graph(4)
with open('test.gpickle', 'wb') as f:
    pickle.dump(G, f, pickle.HIGHEST_PROTOCOL)
with open('test.gpickle', 'rb') as f:
    G = pickle.load(f)**
------------------------------------------------------------
